### ISSUE TITLE
Recursive folder add doesn't always work

### ISSUE THREAD

**Issue by DirtYiCE** [AndreyPavlenko/Fermata#34]
Since 369df98029837baa641fe2de0c82019363448137 Fermata should support recursively adding directories to playlist, however it doesn't seem to always work in practice. I'm not sure what is the problem, since there are no error messages, but I suspect that if there are files that are not yet indexed, it simply fails. If I create a new playlist, it creates an empty list, if I add to an existing one it doesn't do anything. It certainly never worked for me on top level folders. Logcat also seems unhelpful, after clicking on the OK button of the create playlist window:

```
07-10 20:32:39.170 26480 26506 D OpenGLRenderer: endAllActiveAnimators on 0x7a452edf00 (RippleDrawable) with handle 0x7a92c0a7e0
07-10 20:32:39.185  2822 12083 E InputDispatcher: Window handle Window{65c84b4 u0 me.aap.fermata.auto/me.aap.fermata.ui.activity.MainActivity} has no registered input channel
07-10 20:32:39.194 23733 23733 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{688e6bf V.ED..... ......ID 0,0-1080,480 #1020026 android:id/keyboardView}
```

But I get similar output when it actually works. Logcat is from 1.7.0, but 1.8.0 doesn't seem to work either.

**Comment by AndreyPavlenko** [comment]
Thanks. I've reproduced the issue. Should be fixed in the next version.

**Comment by DirtYiCE** [comment]
Just rechecked it 1.8.10, but many times I still get an empty playlist when I create a playlist from a directory. Any idea?

**Comment by DirtYiCE** [comment]
It looks like I had some files that failed indexing with the VLC indexer, but succeeded with the system one, then some file that didn't play with MediaPlayer but does with VLC, now it seems like to work. Until I add some new weird files, I guess.
