### ISSUE TITLE
Auto updates doesnt work

### ISSUE THREAD

**Issue by otromen02** [AndreyPavlenko/Fermata#423]
Hi, my Fermata Auto doesnt trigger auto update anymore, any particular reason?

**Comment by AndreyPavlenko** [comment]
Thanks. Should be fixed in the next version.

**Comment by otromen02** [comment]
Hi, is this issue not yet solved?

**Comment by otromen02** [comment]
I'm still not getting the prompt to update to v1.9.9 when I install v1.9.8

**Comment by AndreyPavlenko** [comment]
Because it's broken in v1.9.8

**Comment by otromen02** [comment]
May I know in which version its working?

**Comment by AndreyPavlenko** [comment]
It's fixed here https://github.com/AndreyPavlenko/Fermata/commit/1d3913989cd028849e1f52d10efdf50a35db8d25 , but probably it's not released yet.

**Comment by otromen02** [comment]
Any previous version that the update checker is working?

**Comment by AndreyPavlenko** [comment]
No, it does not work, because the release content has been changed - there is no fermata control anymore.
